.TH kordquest 6 "May 2019" "Version 1.0"
.SH NAME
kordquest \- a simple text adventure written in Java
.SH SYNOPSIS
.ll +8
.B "javac kordquestRunner.java && java !:1"
.ll -8
.SH DESCRIPTION
KordQuest is a simple text adventure written in Java.
The player starts the game in a small house on a hill,
with a townsperson who will explain the adventure.
The game is not very long, so there is
.B "no save functionality"
built in.
The only way to retain progress is to keep the game running.
.SH PLAYER'S GUIDE
The goal of the game, as explained by Dungarth in the starting
area, is to defeat the evil sorceror Kord at the top of Grand
Mountain. If you die along the way, you must restart the game.
.SS PLAYER COMMANDS
.TP
.B north
Move north.
.TP
.B south
Move south.
.TP
.B east
Move east.
.TP
.B west
Move west.
.TP
.B attack
Attack an enemy in the area.
.TP
.B interact
Interact with objects in the area.
.SH AUTHOR
Andrew Redinbo
.SH SEE ALSO
.B java
(1)
